version: '3.8'
services:
  db:
    image: postgis/postgis:15-3.3
    container_name: varithon-postgis
    environment:
      POSTGRES_USER: varithon
      POSTGRES_PASSWORD: varithon_password
      POSTGRES_DB: varithon_emergency
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  mqtt:
    image: emqx/emqx:5.1
    container_name: varithon-emqx
    environment:
      EMQX_NODE_NAME: emqx@127.0.0.1
      EMQX_HOST: 127.0.0.1
      EMQX_ALLOW_ANONYMOUS: "true"
    ports:
      - "1883:1883"     # MQTT TCP
      - "8083:8083"     # MQTT WebSockets
      - "18083:18083"   # EMQX Dashboard
    restart: unless-stopped

volumes:
  pg_data:
