services:
  - type: web
    name: varithon-backend
    runtime: node
    serviceDirectory: Varithon_Project/backend
    buildCommand: npm install
    startCommand: npm run migrate && npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://varithon-frontend.onrender.com,null

  - type: static_site
    name: varithon-frontend
    serviceDirectory: Varithon_Project/frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE
        value: https://varithon-backend.onrender.com/api
